[tool.black]
line-length = 88
target_version = ['py310']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | env
    | _build
    | buck-out
    | build
    | dist
    | .venv
    | venv
  )/
)
'''


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]
python_files = "test_*.py"

[tool.pyright]
pythonVersion = "3.10"
pythonPlatform = "Linux"
ignore = [
  "cogs/**/*",               # everything, cut this down over time
  "karma/**/*",
  "migrations/versions",
  "utils/announce_utils.py",
  "roll/**/*",
  "tests/**/*",
  "voting/**/*",
  "utils/custom_help.py",
]
# https://microsoft.github.io/pyright/#/configuration?id=diagnostic-rule-defaults

typeCheckingMode = "strict"
useLibraryCodeForTypes = true
reportMissingTypeStubs = false
reportImportCycles = false         # this is actually a big issue but the bad module structure makes it hard to resolve
reportMissingParameterType = false

[tool.ruff]
target-version = "py310"
select = ["E", "F", "I"] # defaults plus isort
ignore = ["E501"]

exclude = ["migrations/versions/*", "models/__init__.py"]
